# Generated by Django 6.0.6 on 2026-06-13 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('IndicatorCode', models.CharField(blank=True, max_length=255, null=True)),
                ('SpatialDimType', models.CharField(blank=True, max_length=255, null=True)),
                ('SpatialDim', models.CharField(blank=True, max_length=255, null=True)),
                ('TimeDimType', models.CharField(blank=True, max_length=255, null=True)),
                ('ParentLocationCode', models.CharField(blank=True, max_length=255, null=True)),
                ('ParentLocation', models.CharField(blank=True, max_length=255, null=True)),
                ('Dim1Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Dim1', models.CharField(blank=True, max_length=255, null=True)),
                ('TimeDim', models.FloatField(blank=True, null=True)),
                ('Dim2Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Dim2', models.CharField(blank=True, max_length=255, null=True)),
                ('Dim3Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Dim3', models.CharField(blank=True, max_length=255, null=True)),
                ('DataSourceDimType', models.CharField(blank=True, max_length=255, null=True)),
                ('DataSourceDim', models.CharField(blank=True, max_length=255, null=True)),
                ('Value', models.CharField(blank=True, max_length=255, null=True)),
                ('NumericValue', models.DecimalField(blank=True, decimal_places=12, max_digits=12, null=True)),
                ('Low', models.CharField(blank=True, max_length=255, null=True)),
                ('High', models.CharField(blank=True, max_length=255, null=True)),
                ('Comments', models.CharField(blank=True, max_length=255, null=True)),
                ('Date', models.CharField(max_length=255)),
                ('TimeDimensionValue', models.CharField(blank=True, max_length=255, null=True)),
                ('TimeDimensionBegin', models.CharField(blank=True, max_length=255, null=True)),
                ('TimeDimensionEnd', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dataset_loader_api_new',
            },
        ),
        migrations.CreateModel(
            name='ApiExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_code', models.CharField(blank=True, max_length=100, null=True)),
                ('indicator_name', models.CharField(blank=True, max_length=250, null=True)),
                ('disease_name', models.CharField(blank=True, max_length=250, null=True)),
                ('country_code', models.CharField(blank=True, max_length=50, null=True)),
                ('country_name', models.CharField(blank=True, max_length=250, null=True)),
                ('parent_location', models.CharField(blank=True, max_length=100, null=True)),
                ('time_dim', models.IntegerField(blank=True, null=True)),
                ('Dim1', models.CharField(blank=True, max_length=250, null=True)),
                ('Dim2', models.CharField(blank=True, max_length=250, null=True)),
                ('Dim3', models.CharField(blank=True, max_length=250, null=True)),
                ('alpha_value', models.CharField(blank=True, max_length=255, null=True)),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('api_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'data_loader_api',
            },
        ),
        migrations.CreateModel(
            name='ApiFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'API Field Configuration',
                'verbose_name_plural': 'API Field Configurations',
                'db_table': 'api_field_config',
            },
        ),
        migrations.CreateModel(
            name='ApiFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_field', models.CharField(max_length=100)),
                ('db_field', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mapping_api_db',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=300, verbose_name='Country name')),
                ('iso3', models.CharField(max_length=300, verbose_name='ISO')),
                ('flag', models.SlugField(blank=True, null=True, verbose_name='Flag')),
                ('city_country', models.CharField(max_length=250, verbose_name='City of country')),
                ('city_ascii', models.CharField(max_length=250, verbose_name='City ascii')),
                ('admin_name', models.CharField(max_length=250, verbose_name='Subregion')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capital', models.CharField(blank=True, max_length=250, null=True, verbose_name='Capital')),
                ('population', models.FloatField(blank=True, null=True, verbose_name='Population')),
            ],
            options={
                'db_table': 'list_city',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=50, verbose_name='Component')),
            ],
            options={
                'db_table': 'list_component',
                'ordering': ['component_name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.SlugField(blank=True, null=True, verbose_name='Flag')),
                ('cca3', models.CharField(max_length=300, verbose_name='ISO')),
                ('name', models.CharField(max_length=300, verbose_name='Country name')),
                ('official', models.CharField(max_length=250, verbose_name='Official')),
                ('capital', models.CharField(max_length=250, verbose_name='Capital')),
                ('subregion', models.CharField(max_length=250, verbose_name='Subregion')),
                ('area', models.CharField(max_length=250, verbose_name='Area')),
                ('population', models.FloatField(verbose_name='Population')),
                ('languages', models.CharField(max_length=250, verbose_name='Languages')),
                ('maps', models.URLField(max_length=500, verbose_name='Maps')),
                ('ref_data', models.CharField(max_length=50, verbose_name='Reference of data')),
                ('data_source', models.URLField(max_length=500, verbose_name='Link')),
                ('country_class', models.CharField(max_length=300, verbose_name='Country class')),
            ],
            options={
                'db_table': 'country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du fichier')),
                ('file_doc', models.ImageField(null=True, upload_to='static/images')),
            ],
            options={
                'db_table': 'picture_loader_cover',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_code', models.CharField(max_length=30, verbose_name='Indicator code')),
                ('indicator_name', models.CharField(max_length=250, verbose_name='Indicator name')),
                ('indicator_description', models.CharField(max_length=250, null=True, verbose_name='Indicator description')),
                ('indicator_target', models.CharField(max_length=250, null=True, verbose_name='Target')),
                ('indicator_metric', models.CharField(max_length=20, null=True, verbose_name='Metric')),
                ('indicator_unit', models.CharField(max_length=50, null=True, verbose_name='Unit of measurement')),
                ('indicator_frequency', models.CharField(max_length=250, null=True, verbose_name='Indicator frequency')),
                ('indicator_source', models.URLField(max_length=500, verbose_name='Link')),
                ('category_indicator', models.CharField(choices=[('Prevalence', 'Prevalence'), ('Incidence', 'Incidence'), ('Death', 'Death'), ('Strategy', 'Strategy')], max_length=10, null=True, verbose_name='Category')),
                ('forecasting_indicator', models.CharField(choices=[('sir', 'SIR'), ('arima', 'ARIMA'), ('ACP', 'ACP'), ('ACM', 'ACM'), ('None', 'None')], max_length=10, null=True, verbose_name='Forecasting')),
                ('performance_indicator', models.CharField(choices=[('Low', 'Low'), ('High', 'High'), ('Constant', 'Constant')], max_length=10, null=True, verbose_name='Performance')),
                ('type_indicator', models.CharField(choices=[('Quanti_ind', 'Quantitatif'), ('Quali_ind', 'Qualitatif')], max_length=15, null=True, verbose_name='Type of indicator')),
                ('ref_data', models.CharField(max_length=50, verbose_name='Reference of data')),
            ],
            options={
                'db_table': 'list_indicator',
            },
        ),
        migrations.CreateModel(
            name='LocationCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3', models.CharField(max_length=300, verbose_name='ISO')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'location_country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_rep', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre du rapport')),
                ('author_rep', models.CharField(blank=True, max_length=500, null=True, verbose_name='Organisation responsable')),
                ('date_rep', models.DateField(blank=True, verbose_name='Date')),
                ('summary_rep', models.CharField(max_length=500, verbose_name='Résumé')),
                ('file_rep', models.FileField(null=True, upload_to='static/report/pdf')),
                ('img_cp_rep', models.ImageField(null=True, upload_to='static/report/picture')),
            ],
            options={
                'db_table': 'report_loader',
            },
        ),
        migrations.CreateModel(
            name='StoreAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('indicator_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicator code')),
                ('country_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country code')),
                ('dim1_type', models.CharField(blank=True, max_length=255, null=True)),
                ('dim1', models.CharField(blank=True, max_length=255, null=True)),
                ('dim2_type', models.CharField(blank=True, max_length=255, null=True)),
                ('dim2', models.CharField(blank=True, max_length=255, null=True)),
                ('dim3_type', models.CharField(blank=True, max_length=255, null=True)),
                ('dim3', models.CharField(blank=True, max_length=255, null=True)),
                ('time_dim', models.FloatField(blank=True, null=True)),
                ('alpha_value', models.CharField(blank=True, max_length=255, null=True)),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('publish_date', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'store_api',
            },
        ),
        migrations.CreateModel(
            name='SurveyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(blank=True, max_length=500, null=True, verbose_name='Organisation responsable')),
                ('title_surv', models.CharField(blank=True, max_length=350, null=True, verbose_name='Sujet de l’enquête')),
                ('target_population', models.CharField(blank=True, max_length=350, null=True, verbose_name='Population cible')),
                ('start_date', models.DateField(blank=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, verbose_name='Date de fin')),
                ('location_survey', models.CharField(blank=True, max_length=500, null=True, verbose_name='Lieu de l’enquête')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'survey_project',
            },
        ),
        migrations.CreateModel(
            name='WarehouseScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ws_title', models.CharField(max_length=250, null=True, verbose_name='Nom enquête')),
                ('ws_type', models.CharField(choices=[('E', 'Empirique'), ('S', 'Surveillance')], max_length=20, verbose_name='Type de collecte')),
                ('ws_table', models.CharField(max_length=250, null=True, verbose_name='Nom table')),
                ('ws_create', models.CharField(max_length=500, null=True, verbose_name='Script CREATE')),
                ('ws_insert', models.CharField(max_length=500, null=True, verbose_name='Script INSERT')),
                ('ws_select', models.CharField(max_length=500, null=True, verbose_name='Script SELECT')),
                ('ws_join', models.CharField(max_length=500, null=True, verbose_name='Script JOIN')),
                ('ws_pivot', models.CharField(max_length=500, null=True, verbose_name='Script PIVOT')),
                ('ws_pathfile', models.CharField(max_length=500, null=True, verbose_name='Chemin fichier')),
                ('ws_focalpoint', models.CharField(max_length=200, null=True, verbose_name='Point focal')),
                ('ws_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scripts_warehouse',
            },
        ),
        migrations.CreateModel(
            name='RepositoryIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='Indicator code')),
                ('spatial_dim', models.CharField(blank=True, max_length=250, null=True, verbose_name='Spatial Dim')),
                ('dim1_type', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dim1 type')),
                ('dim1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dim1')),
                ('dim2_type', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dim2 type')),
                ('dim2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dim2')),
                ('dim3_type', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dim3 type')),
                ('dim3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dim3')),
                ('time_dim', models.FloatField(blank=True, null=True, verbose_name='Time')),
                ('alpha_value', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Alpha-numeric value')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Numerical value')),
                ('publish_date', models.DateField(blank=True, verbose_name='Date of publication')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_repository', to='mytvddata.country')),
                ('indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_repository', to='mytvddata.indicator')),
            ],
            options={
                'db_table': 'data_loader_repository',
            },
        ),
        migrations.CreateModel(
            name='Subcomponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcomponent_name', models.CharField(max_length=250, null=True, verbose_name='Disease')),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comp_subcomponent', to='mytvddata.component')),
            ],
            options={
                'db_table': 'list_subcomponent',
                'ordering': ['subcomponent_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Country Code')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grade')),
                ('name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telephone')),
                ('office_affiliation', models.CharField(blank=True, max_length=150, null=True, verbose_name='Office Affiliation')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Position')),
                ('responsibility', models.TextField(blank=True, null=True, verbose_name='Responsibility')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Language')),
                ('level_geo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Geographical Level')),
                ('diseases', models.ManyToManyField(blank=True, related_name='staff_members', to='mytvddata.subcomponent')),
            ],
            options={
                'db_table': 'staff_member',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='subcomponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcomponent_indicator', to='mytvddata.subcomponent'),
        ),
        migrations.CreateModel(
            name='SurveyDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='Code question')),
                ('question', models.CharField(max_length=1000, verbose_name='Question')),
                ('response_text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Réponse texte')),
                ('response_num', models.FloatField(blank=True, null=True, verbose_name='Réponse numérique')),
                ('level_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dimension spatiale 1')),
                ('level_2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dimension spatiale 2')),
                ('surveyProject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_surveyData', to='mytvddata.surveyproject')),
            ],
            options={
                'db_table': 'data_loader_survey',
            },
        ),
    ]
