# Generated by Django 6.0.6 on 2026-06-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytvddata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='countries',
            field=models.ManyToManyField(blank=True, to='mytvddata.country'),
        ),
    ]
