# Generated by Django 6.0.6 on 2026-06-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytvddata', '0002_staffmember_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmember',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='country',
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='language',
            field=models.JSONField(blank=True, null=True, verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='country',
            field=models.ManyToManyField(blank=True, to='mytvddata.country'),
        ),
    ]
