# Generated by Django 6.0.6 on 2026-06-21 20:00

from django.db import migrations, models
import json

def convert_jsonfield_to_textfield(apps, schema_editor):
    StaffMember = apps.get_model("mytvddata", "StaffMember")
    for staff in StaffMember.objects.all():
        # Si data était JSONField, on le convertit en texte
        if isinstance(staff.data, (dict, list)):
            staff.data = json.dumps(staff.data)
            staff.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mytvddata', '0002_staffmember_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmember',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='country',
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='language',
            field=models.TextField(blank=True, null=True, verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='country',
            field=models.ManyToManyField(blank=True, to='mytvddata.country'),
        ),
    ]
