# Generated by Django 6.0.6 on 2026-08-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytvddata', '0003_alter_staffmember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='indicator_code',
            field=models.CharField(max_length=250, verbose_name='Indicator code'),
        ),
        migrations.AlterField(
            model_name='repositoryindicator',
            name='numeric_value',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=18, null=True, verbose_name='Numerical value'),
        ),
    ]
