"""
Django settings for TVDdata project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


#import yaml
import os
from pathlib import Path

#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Charger le fichier YAML
#with open(os.path.join(BASE_DIR, "config.yaml"), "r") as f:
 #    yaml_config = yaml.safe_load(f)

# Choisir l'environnement (par défaut: dev)
#env = os.getenv("DJANGO_ENV", "dev")

#DATABASES = {
#    "default": yaml_config["database"][env]
#}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-en0lhq9jy2kx$q4&^dijb8s6()r1h*nrb%g39v7dsvc)-g@(_h'

# SECURITY WARNING: don't run with debug turned on in production!


# Choix de l'environnement : dev ou prod
ENV = os.getenv("DJANGO_ENV", "dev")

DEBUG = ENV == "dev"
#DEBUG = True

ALLOWED_HOSTS = ['*']  if DEBUG else ["localhost", "127.0.0.1", "yourdomain.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mytvddata.apps.MytvddataConfig',
    'crispy_forms',
    'crispy_bootstrap4',
    'rest_framework',
   # 'django_countries',+------------------------------
   # 'django_filter',
    'lockdown',
   # 'weasyprint',
   # 'xhtml2pdf',
    'widget_tweaks',
   'import_export',
]
# Choisis le pack de templates
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"


# Ajout d’outils dev uniquement
if ENV == "dev":
    INSTALLED_APPS += ["debug_toolbar"]

MIDDLEWARE = [
   "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # <--- important pour Docker
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django_auto_logout.middleware.auto_logout', # Django auto logout (1)
 

]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

if ENV == "dev":
    MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]

ROOT_URLCONF = 'TVDdata.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_auto_logout.context_processors.auto_logout_client', # Django auto logout (2)
            ],
        },
    },
]

WSGI_APPLICATION = 'TVDdata.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}
# DATABASES = {
#     'default': {
#        'ENGINE': 'mssql',
#         'NAME': 'tvd_dts',#'tvd_db',              # Exemple : TVD_DB
#         'HOST': 'DESKTOP-QVJV7NQ',    # ou ton serveur SQL # DESKTOP-QVJV7NQ
#         'PORT': '',                         # vide = port par défaut
#         'USER': '',                         # vide car Windows Auth
#         'PASSWORD': '',                     # vide car Windows Auth
#         'OPTIONS': {
#             'driver': 'ODBC Driver 17 for SQL Server',
#             'trusted_connection': 'yes',    # Authentification Windows
#             'TrustServerCertificate': 'yes' # accepte certificat auto-signé
#         },
#     }
# }

if ENV == "dev":
    # Connexion locale avec authentification Windows
    DATABASES = {
        "default": {
            "ENGINE": "mssql",
            "NAME": os.getenv("DB_NAME", "tvd_dts"),
            "HOST": os.getenv("DB_HOST", "DESKTOP-QVJV7NQ"),
            "OPTIONS": {
                "driver": "ODBC Driver 17 for SQL Server",
                "trusted_connection": "yes",
                "TrustServerCertificate": "yes",
            },
        }
    }
else:
    # Connexion en production avec utilisateur SQL
    DATABASES = {
        "default": {
            "ENGINE": "mssql", #sql_server.pyodbc
            "NAME": os.getenv("DB_NAME", "TVDdata"),
            "HOST": os.getenv("DB_HOST", "db"),
            "PORT": os.getenv("DB_PORT", "1433"),
            "USER": os.getenv("DB_USER", "sa"),
            "PASSWORD": os.getenv("DB_PASSWORD", "Reine2009#"),
            "OPTIONS": {
                "driver": "ODBC Driver 17 for SQL Server",
                "TrustServerCertificate": "yes",
            },
        }
    }



 


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

#USE_I18N = True

USE_TZ = True



USE_I18N = True
USE_L10N = True

#LANGUAGE_CODE = 'en'   # langue par défaut

LANGUAGES = [
    ('en', 'English'),
    ('fr', 'Français'),
    ('pt', 'Português'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/



#if DEBUG:

STATIC_URL = "static/"


STATICFILES_DIRS = [
        BASE_DIR / "static",
        BASE_DIR / "static/js",
        BASE_DIR / "static/images",
        BASE_DIR / "static/report",
        BASE_DIR / "static/upload",
    ]

STATIC_ROOT = BASE_DIR / "staticfiles"



#STATIC_URL = 'static/'

#STATIC_ROOT = BASE_DIR / 'staticfiles'

AUTO_LOGOUT = {'IDLE_TIME': 1200, 'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
               'MESSAGE': 'The session has expired. Please login again to continue.',}  # logout after 10 minutes of downtime (4)
 

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# Default primary key field type

# =========================
# Sécurité Prod
# =========================
if ENV == "prod":
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
 