"""
Django settings for TVDdata project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
#import yaml
import os

#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Charger le fichier YAML
#with open(os.path.join(BASE_DIR, "config.yaml"), "r") as f:
 #    yaml_config = yaml.safe_load(f)

# Choisir l'environnement (par défaut: dev)
#env = os.getenv("DJANGO_ENV", "dev")

#DATABASES = {
#    "default": yaml_config["database"][env]
#}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-en0lhq9jy2kx$q4&^dijb8s6()r1h*nrb%g39v7dsvc)-g@(_h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] # For local


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mytvddata.apps.MytvddataConfig',
    'crispy_forms',
    'crispy_bootstrap4',
    'rest_framework',
   # 'django_countries',
   # 'django_filter',
    'lockdown',
    'widget_tweaks',
   'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TVDdata.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TVDdata.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'tvd_dts',#'tvd_db',              # Exemple : TVD_DB
        'HOST': 'DESKTOP-QVJV7NQ',    # ou ton serveur SQL
        'PORT': '',                         # vide = port par défaut
        'USER': '',                         # vide car Windows Auth
        'PASSWORD': '',                     # vide car Windows Auth
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trusted_connection': 'yes',    # Authentification Windows
            'TrustServerCertificate': 'yes' # accepte certificat auto-signé
        },
    }
}


#DATABASES = {
#    'default': {
#        'ENGINE': 'mssql',
#        'NAME': 'tvd_db',
#        'USER': 'sa',
#        'PASSWORD': 'VotreMotDePasse123',
#        'HOST': 'localhost',
#       'PORT': '1433',
#        'OPTIONS': {
#            'driver': 'ODBC Driver 17 for SQL Server',
#        },
#   }
#}
 


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

#STATIC_URL = 'static/'
STATIC_URL = '/static/'
#STATICFILES_DIRS = [BASE_DIR / "static"]

 
if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] # for deploy use staticfiles
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static') # for deploy use static
 
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
 
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#DYNAMIC_DATATB={
#    'indicators':"app.models.Indicator",
#}

 